{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: details
  labels:
    app: details
    chart: {{ template "bookinfo-details.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: details
{{- end }}
