apiVersion: v1
description: OpenLDAP Chart for IBM Cloud Paks
name: cp-openldap
version: 0.3.0
keywords: [ldap]
home: https://www.openldap.ort
sources:
  - https://github.com/openldap/openldap
icon: https://raw.githubusercontent.com/styblope/helm-charts/master/cp-openldap/icon.png
maintainers:
  - name: Petr Styblo
    email: petr.styblo@cz.ibm.com
engine: gotpl
