apiVersion: v1
kind: ServiceAccount
metadata:
  name: openldap
  labels:
    app: {{.Release.Name}}
  name: {{.Release.Name}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: {{.Release.Name}}
  name: {{.Release.Name}}-anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: openldap
  namespace: {{.Release.Namespace}}
