bookinfo-details:
  version: v1
  replicas: 1
bookinfo-ratings:
  version: v1
  replicas: 1
bookinfo-reviews:
  version: v1
  replicas: 1
bookinfo-productpage:
  version: v1
  replicas: 1

openshift-route:
  enabled: true
  fullnameOverride: bookinfo
  service:
    name: productpage
