{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    app: ratings
    chart: {{ template "bookinfo-ratings.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ratings
{{- end }}