apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  metadata:
  name: reviews-{{ .Values.version }}
  labels:
    app: reviews
    version: "{{ .Values.version }}"
    chart: {{ template "bookinfo-reviews.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: reviews
      version: "{{ .Values.version }}"
  template:
    metadata:
      labels:
        app: reviews
        version: "{{ .Values.version }}"
        chart: {{ template "bookinfo-reviews.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: reviews
        image: istio/examples-bookinfo-reviews-{{ .Values.version }}:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9080
          protocol: TCP
        {{- if .Values.probesEnabled }}
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 5
          periodSeconds: 5
        {{- end }}
